## Application Name
#spring:
#  application:
#    name: product-service
#
## Database Config
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:product
#    username: user
#    password: 123
#    driverClassName: org.h2.Driver
#
## Feing Clieng Config
#  cloud:
#    openfeign:
#      client:
#        config:
#          installmentClient:
#            connect-timeout: 5000
#            read-timeout: 5000
#            logger-level: full
#            url: http://localhost:8090/installment-service
#
## Server Port
#server:
#  port: 8080
## Root Path Config  
#  servlet:
#    context-path: /product-service
#    
##installment-service:
##  url: localhost:8090/