INSERT INTO TB_PRODUCT (ID, NAME, PRICE, TOTAL_INSTALLMENT, HAS_RATE) VALUES (1, 'Smartphone Samsung A15 - 4GB RAM - 64GB', 1159.90, 12, false);
INSERT INTO TB_PRODUCT (ID, NAME, PRICE, TOTAL_INSTALLMENT, HAS_RATE) VALUES (2, 'Smartphone LG K52 - 3GB RAM - 62GB', 799.90, 12, false);
INSERT INTO TB_PRODUCT (ID, NAME, PRICE, TOTAL_INSTALLMENT, HAS_RATE) VALUES (3, 'Smartphone ASUS Zenfone 8 - 8GB RAM - 128GB', 2259.90, 12, true);
INSERT INTO TB_PRODUCT (ID, NAME, PRICE, TOTAL_INSTALLMENT, HAS_RATE) VALUES (4, 'Smartphone Motorola Eedg 40 Neo - 16GB RAM - 256GB', 1799.90, 12, true);